### ISSUE TITLE
Doesn't close gracefully when closed from the logic-thread.

### ISSUE THREAD

**Issue by zaafar** [zaafar/ClickableTransparentOverlay#17]
User of this library have to implement special logic so that only the render thread calls the close operation.

**Comment by zaafar** [comment]
@Amiron49  any idea on how to solve this? I am thinking of bringing back the old close mechanism i.e. any thread can **ask for close** and whenever render thread gets the time, it will close the overlay.

**Comment by Amiron49** [comment]
Just to be clear: 

Is the behavior you observe that when you call a `this.Dispose()` in the logic thread that an exception gets thrown or that when you call `this.Close().Wait()` the program doesn't terminate?

**Comment by zaafar** [comment]
this.Close().Wait() and the program doesn't terminate.

**Comment by Amiron49** [comment]
As far as I can tell it's the logic thread that keeps the program alive and not the overlay. The while loop needs `state.IsRunning` to be set to false or else that thread will just live forever.

**Comment by zaafar** [comment]
Yes, you are correct. Once I set `state.IsRunning = false;` in the logic thread, the overlay closed. I wonder if DRY out this logic and move move it to the `abstract overlay class`. Otherwise every user of this library have to implement this logic in the `Derived Overlay Class`.

**Comment by zaafar** [comment]
-> so custom logic could be run when called. 

Not following this logic, how would custom logic would help in this scenario.
A sample implementation would be nice.

**Comment by Amiron49** [comment]
If I'm understanding you right then you want to expose the overlays current "running" state so code outside can react to changes to it right? If that is what you meant then I'm totally for it. If you are talking about implementing the "logic thread" into the overlay then I'd be against it because I'm already an example of someone who doesn't need a logic thread as I'm using the overlay within a QT GUI. 

with "so custom logic could be run when called." I meant that as this example implementation enhanced the overlay with a logic thread it may want to be able to hook into the Close() lifecycle method to do it's own additional closing logic like setting that flag to false to stop the thread

I saw your "nvm, i see your point." edit but I don't want to delete everything I wrote so far ;_;

**Comment by zaafar** [comment]
-> If I'm understanding you right then you want to expose the overlays current "running" state so code outside can react to changes to it right

overall, I think both custom logic or this one is fine. Custom logic is a bit better because it gives user more flexibility.
